# Generated by Django 3.1.1 on 2020-09-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('href', models.URLField()),
                ('img', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
            ],
        ),
    ]
