# Generated by Django 3.1.1 on 2020-09-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField()),
                ('img', models.TextField()),
                ('title', models.TextField()),
                ('players', models.TextField()),
            ],
        ),
    ]
