# Generated by Django 3.1.1 on 2020-09-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webpage', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField()),
                ('img', models.TextField()),
                ('title', models.TextField()),
                ('players', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField()),
                ('img', models.TextField()),
                ('title', models.TextField()),
                ('players', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Goods',
            new_name='Con',
        ),
    ]
