# Generated by Django 3.1.1 on 2020-09-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webpage', '0003_auto_20200925_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField()),
                ('img', models.TextField()),
                ('title', models.TextField()),
                ('players', models.TextField()),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Con',
        ),
        migrations.DeleteModel(
            name='Exh',
        ),
        migrations.DeleteModel(
            name='Play',
        ),
        migrations.AlterField(
            model_name='category',
            name='goods_num',
            field=models.CharField(max_length=20),
        ),
    ]
