# Generated by Django 3.1.1 on 2020-09-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_webpage', '0004_auto_20200925_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='goods_num',
            new_name='category',
        ),
    ]
